### ISSUE TITLE
ng-up template scans through node_modules

### ISSUE THREAD

**Issue by ellamaolson** [psmyrdek/ng-up#28]
When I run either:
```
ng-up template 
```
```
ng-up template -d
```
I notice the files it scans through are mostly in node_modules, though once actually executing the program, nothing in node_modules is changed. It would be helpful it the program ignored node_modules when scanning through the directory so it does not print node_modules files.

**Comment by psmyrdek** [comment]
Thanks for opening this issue. Will take a look at this soon.

**Comment by psmyrdek** [comment]
@ellamaolson `template` command requires a `pattern` parameter to limit the directories to scan - this parameter is missing based on your comment. I'm gonna improve error handling for such issues in the future.
